// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v4.1.0
// - protoc              v3.19.6
// source: main.proto

package pb

import (
	context "context"
	client "go.unistack.org/micro/v4/client"
)

var (
	BookServerName = "BookServer"
)

type BookServerClient interface {
	Home(ctx context.Context, req *EmptyReq, opts ...client.CallOption) (*StatusRsp, error)
	Push(ctx context.Context, req *PostBookReq, opts ...client.CallOption) (*StatusUploadedBookRsp, error)
	Book(ctx context.Context, req *GetBookReq, opts ...client.CallOption) (*GetBookRsp, error)
	GetAllBooks(ctx context.Context, req *EmptyReq, opts ...client.CallOption) (*GetAllBooksRsp, error)
	GetAllBooksAndSort(ctx context.Context, req *SortTypeReq, opts ...client.CallOption) (*GetAllBooksAndSortRsp, error)
}

type BookServerServer interface {
	Home(ctx context.Context, req *EmptyReq, rsp *StatusRsp) error
	Push(ctx context.Context, req *PostBookReq, rsp *StatusUploadedBookRsp) error
	Book(ctx context.Context, req *GetBookReq, rsp *GetBookRsp) error
	GetAllBooks(ctx context.Context, req *EmptyReq, rsp *GetAllBooksRsp) error
	GetAllBooksAndSort(ctx context.Context, req *SortTypeReq, rsp *GetAllBooksAndSortRsp) error
}
