// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v4.1.0
// source: main.proto

package pb

import (
	context "context"
	v41 "go.unistack.org/micro-client-http/v4"
	v4 "go.unistack.org/micro-server-http/v4"
	client "go.unistack.org/micro/v4/client"
	server "go.unistack.org/micro/v4/server"
	http "net/http"
	time "time"
)

var (
	BookServerServerEndpoints = []v4.EndpointMetadata{
		{
			Name:   "BookServer.Home",
			Path:   "/",
			Method: "GET",
			Body:   "*",
			Stream: false,
		},
		{
			Name:   "BookServer.Push",
			Path:   "/push",
			Method: "POST",
			Body:   "*",
			Stream: false,
		},
		{
			Name:   "BookServer.Book",
			Path:   "/book",
			Method: "GET",
			Body:   "*",
			Stream: false,
		},
		{
			Name:   "BookServer.GetAllBooks",
			Path:   "/allbooks",
			Method: "GET",
			Body:   "*",
			Stream: false,
		},
		{
			Name:   "BookServer.GetAllBooksAndSort",
			Path:   "/allbooks",
			Method: "GET",
			Body:   "*",
			Stream: false,
		},
	}
)

type bookServerClient struct {
	c    client.Client
	name string
}

func NewBookServerClient(name string, c client.Client) BookServerClient {
	return &bookServerClient{c: c, name: name}
}

func (c *bookServerClient) Home(ctx context.Context, req *EmptyReq, opts ...client.CallOption) (*StatusRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &ErrorRsp{}
	opts = append(opts,
		v41.ErrorMap(errmap),
	)
	opts = append(opts,
		v41.Method(http.MethodGet),
		v41.Path("/"),
		v41.Body("*"),
	)
	td := time.Duration(1000000000)
	opts = append(opts, client.WithRequestTimeout(td))
	rsp := &StatusRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "BookServer.Home", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *bookServerClient) Push(ctx context.Context, req *PostBookReq, opts ...client.CallOption) (*StatusUploadedBookRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &ErrorRsp{}
	opts = append(opts,
		v41.ErrorMap(errmap),
	)
	opts = append(opts,
		v41.Method(http.MethodPost),
		v41.Path("/push"),
		v41.Body("*"),
	)
	td := time.Duration(1000000000)
	opts = append(opts, client.WithRequestTimeout(td))
	rsp := &StatusUploadedBookRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "BookServer.Push", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *bookServerClient) Book(ctx context.Context, req *GetBookReq, opts ...client.CallOption) (*GetBookRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &ErrorRsp{}
	opts = append(opts,
		v41.ErrorMap(errmap),
	)
	opts = append(opts,
		v41.Method(http.MethodGet),
		v41.Path("/book"),
		v41.Body("*"),
	)
	td := time.Duration(1000000000)
	opts = append(opts, client.WithRequestTimeout(td))
	rsp := &GetBookRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "BookServer.Book", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *bookServerClient) GetAllBooks(ctx context.Context, req *EmptyReq, opts ...client.CallOption) (*GetAllBooksRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &ErrorRsp{}
	opts = append(opts,
		v41.ErrorMap(errmap),
	)
	opts = append(opts,
		v41.Method(http.MethodGet),
		v41.Path("/allbooks"),
		v41.Body("*"),
	)
	td := time.Duration(1000000000)
	opts = append(opts, client.WithRequestTimeout(td))
	rsp := &GetAllBooksRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "BookServer.GetAllBooks", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *bookServerClient) GetAllBooksAndSort(ctx context.Context, req *SortTypeReq, opts ...client.CallOption) (*GetAllBooksAndSortRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &ErrorRsp{}
	opts = append(opts,
		v41.ErrorMap(errmap),
	)
	opts = append(opts,
		v41.Method(http.MethodGet),
		v41.Path("/allbooks"),
		v41.Body("*"),
	)
	td := time.Duration(1000000000)
	opts = append(opts, client.WithRequestTimeout(td))
	rsp := &GetAllBooksAndSortRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "BookServer.GetAllBooksAndSort", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

type bookServerServer struct {
	BookServerServer
}

func (h *bookServerServer) Home(ctx context.Context, req *EmptyReq, rsp *StatusRsp) error {
	var cancel context.CancelFunc
	td := time.Duration(1000000000)
	ctx, cancel = context.WithTimeout(ctx, td)
	defer cancel()
	return h.BookServerServer.Home(ctx, req, rsp)
}

func (h *bookServerServer) Push(ctx context.Context, req *PostBookReq, rsp *StatusUploadedBookRsp) error {
	var cancel context.CancelFunc
	td := time.Duration(1000000000)
	ctx, cancel = context.WithTimeout(ctx, td)
	defer cancel()
	return h.BookServerServer.Push(ctx, req, rsp)
}

func (h *bookServerServer) Book(ctx context.Context, req *GetBookReq, rsp *GetBookRsp) error {
	var cancel context.CancelFunc
	td := time.Duration(1000000000)
	ctx, cancel = context.WithTimeout(ctx, td)
	defer cancel()
	return h.BookServerServer.Book(ctx, req, rsp)
}

func (h *bookServerServer) GetAllBooks(ctx context.Context, req *EmptyReq, rsp *GetAllBooksRsp) error {
	var cancel context.CancelFunc
	td := time.Duration(1000000000)
	ctx, cancel = context.WithTimeout(ctx, td)
	defer cancel()
	return h.BookServerServer.GetAllBooks(ctx, req, rsp)
}

func (h *bookServerServer) GetAllBooksAndSort(ctx context.Context, req *SortTypeReq, rsp *GetAllBooksAndSortRsp) error {
	var cancel context.CancelFunc
	td := time.Duration(1000000000)
	ctx, cancel = context.WithTimeout(ctx, td)
	defer cancel()
	return h.BookServerServer.GetAllBooksAndSort(ctx, req, rsp)
}

func RegisterBookServerServer(s server.Server, sh BookServerServer, opts ...server.HandlerOption) error {
	type bookServer interface {
		Home(ctx context.Context, req *EmptyReq, rsp *StatusRsp) error
		Push(ctx context.Context, req *PostBookReq, rsp *StatusUploadedBookRsp) error
		Book(ctx context.Context, req *GetBookReq, rsp *GetBookRsp) error
		GetAllBooks(ctx context.Context, req *EmptyReq, rsp *GetAllBooksRsp) error
		GetAllBooksAndSort(ctx context.Context, req *SortTypeReq, rsp *GetAllBooksAndSortRsp) error
	}
	type BookServer struct {
		bookServer
	}
	h := &bookServerServer{sh}
	opts = append(opts, v4.HandlerEndpoints(BookServerServerEndpoints))
	return s.Handle(s.NewHandler(&BookServer{h}, opts...))
}
