// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.10.4
// source: main.proto

package pb

import (
	context "context"
	v3 "go.unistack.org/micro-client-http/v3"
	v31 "go.unistack.org/micro-server-http/v3"
	client "go.unistack.org/micro/v3/client"
	server "go.unistack.org/micro/v3/server"
	http "net/http"
)

type bookServerClient struct {
	c    client.Client
	name string
}

func NewBookServerClient(name string, c client.Client) BookServerClient {
	return &bookServerClient{c: c, name: name}
}

func (c *bookServerClient) Home(ctx context.Context, req *Empty, opts ...client.CallOption) (*StatusRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &StatusRsp{}
	opts = append(opts,
		v3.ErrorMap(errmap),
	)
	opts = append(opts,
		v3.Method(http.MethodGet),
		v3.Path("/"),
	)
	rsp := &StatusRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "BookServer.Home", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *bookServerClient) Push(ctx context.Context, req *PostBook, opts ...client.CallOption) (*StatusUploadedBookRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &StatusRsp{}
	opts = append(opts,
		v3.ErrorMap(errmap),
	)
	opts = append(opts,
		v3.Method(http.MethodPost),
		v3.Path("/push"),
		v3.Body("*"),
	)
	rsp := &StatusUploadedBookRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "BookServer.Push", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *bookServerClient) Book(ctx context.Context, req *GetBook, opts ...client.CallOption) (*GetBookRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &StatusRsp{}
	opts = append(opts,
		v3.ErrorMap(errmap),
	)
	opts = append(opts,
		v3.Method(http.MethodGet),
		v3.Path("/book"),
	)
	rsp := &GetBookRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "BookServer.Book", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *bookServerClient) GetAllBooks(ctx context.Context, req *Empty, opts ...client.CallOption) (*GetAllBooks, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &StatusRsp{}
	opts = append(opts,
		v3.ErrorMap(errmap),
	)
	opts = append(opts,
		v3.Method(http.MethodGet),
		v3.Path("/allbooks"),
	)
	rsp := &GetAllBooks{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "BookServer.GetAllBooks", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *bookServerClient) GetAllBooksAndSort(ctx context.Context, req *SortType, opts ...client.CallOption) (*GetAllBooksAndSort, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &StatusRsp{}
	opts = append(opts,
		v3.ErrorMap(errmap),
	)
	opts = append(opts,
		v3.Method(http.MethodGet),
		v3.Path("/books"),
	)
	rsp := &GetAllBooksAndSort{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "BookServer.GetAllBooksAndSort", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

type bookServerServer struct {
	BookServerServer
}

func (h *bookServerServer) Home(ctx context.Context, req *Empty, rsp *StatusRsp) error {
	return h.BookServerServer.Home(ctx, req, rsp)
}

func (h *bookServerServer) Push(ctx context.Context, req *PostBook, rsp *StatusUploadedBookRsp) error {
	return h.BookServerServer.Push(ctx, req, rsp)
}

func (h *bookServerServer) Book(ctx context.Context, req *GetBook, rsp *GetBookRsp) error {
	return h.BookServerServer.Book(ctx, req, rsp)
}

func (h *bookServerServer) GetAllBooks(ctx context.Context, req *Empty, rsp *GetAllBooks) error {
	return h.BookServerServer.GetAllBooks(ctx, req, rsp)
}

func (h *bookServerServer) GetAllBooksAndSort(ctx context.Context, req *SortType, rsp *GetAllBooksAndSort) error {
	return h.BookServerServer.GetAllBooksAndSort(ctx, req, rsp)
}

func RegisterBookServerServer(s server.Server, sh BookServerServer, opts ...server.HandlerOption) error {
	type bookServer interface {
		Home(ctx context.Context, req *Empty, rsp *StatusRsp) error
		Push(ctx context.Context, req *PostBook, rsp *StatusUploadedBookRsp) error
		Book(ctx context.Context, req *GetBook, rsp *GetBookRsp) error
		GetAllBooks(ctx context.Context, req *Empty, rsp *GetAllBooks) error
		GetAllBooksAndSort(ctx context.Context, req *SortType, rsp *GetAllBooksAndSort) error
	}
	type BookServer struct {
		bookServer
	}
	h := &bookServerServer{sh}
	var nopts []server.HandlerOption
	nopts = append(nopts, v31.HandlerEndpoints(BookServerServerEndpoints))
	return s.Handle(s.NewHandler(&BookServer{h}, append(nopts, opts...)...))
}
