// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.4
// - protoc              v3.19.6
// source: main.proto

package pb

import (
	context "context"
	v3 "go.unistack.org/micro-server-http/v3"
	client "go.unistack.org/micro/v3/client"
)

var (
	ServerName = "Server"
)
var (
	ServerServerEndpoints = []v3.EndpointMetadata{
		{
			Name:   "Server.HOME",
			Path:   "/",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
		{
			Name:   "Server.PUSH",
			Path:   "/push",
			Method: "POST",
			Body:   "*",
			Stream: false,
		},
		{
			Name:   "Server.GET",
			Path:   "/push",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
	}
)

type ServerClient interface {
	HOME(ctx context.Context, req *Empty, opts ...client.CallOption) (*StatusRsp, error)
	PUSH(ctx context.Context, req *PostBook, opts ...client.CallOption) (*StatusUploadedBookRsp, error)
	GET(ctx context.Context, req *GetBookReq, opts ...client.CallOption) (*GetBookRsp, error)
}

type ServerServer interface {
	HOME(ctx context.Context, req *Empty, rsp *StatusRsp) error
	PUSH(ctx context.Context, req *PostBook, rsp *StatusUploadedBookRsp) error
	GET(ctx context.Context, req *GetBookReq, rsp *GetBookRsp) error
}
