// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: main.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "go.unistack.org/micro-proto/v3/api"
	_ "go.unistack.org/micro-proto/v3/openapiv3"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for BookServer service

func NewBookServerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for BookServer service

type BookServerService interface {
	Home(ctx context.Context, in *Empty, opts ...client.CallOption) (*StatusRsp, error)
	Push(ctx context.Context, in *PostBook, opts ...client.CallOption) (*StatusUploadedBookRsp, error)
	Book(ctx context.Context, in *GetBook, opts ...client.CallOption) (*GetBookRsp, error)
	GetAllBooks(ctx context.Context, in *Empty, opts ...client.CallOption) (*GetAllBooks, error)
	GetAllBooksAndSort(ctx context.Context, in *SortType, opts ...client.CallOption) (*GetAllBooksAndSort, error)
}

type bookServerService struct {
	c    client.Client
	name string
}

func NewBookServerService(name string, c client.Client) BookServerService {
	return &bookServerService{
		c:    c,
		name: name,
	}
}

func (c *bookServerService) Home(ctx context.Context, in *Empty, opts ...client.CallOption) (*StatusRsp, error) {
	req := c.c.NewRequest(c.name, "BookServer.Home", in)
	out := new(StatusRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServerService) Push(ctx context.Context, in *PostBook, opts ...client.CallOption) (*StatusUploadedBookRsp, error) {
	req := c.c.NewRequest(c.name, "BookServer.Push", in)
	out := new(StatusUploadedBookRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServerService) Book(ctx context.Context, in *GetBook, opts ...client.CallOption) (*GetBookRsp, error) {
	req := c.c.NewRequest(c.name, "BookServer.Book", in)
	out := new(GetBookRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServerService) GetAllBooks(ctx context.Context, in *Empty, opts ...client.CallOption) (*GetAllBooks, error) {
	req := c.c.NewRequest(c.name, "BookServer.GetAllBooks", in)
	out := new(GetAllBooks)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServerService) GetAllBooksAndSort(ctx context.Context, in *SortType, opts ...client.CallOption) (*GetAllBooksAndSort, error) {
	req := c.c.NewRequest(c.name, "BookServer.GetAllBooksAndSort", in)
	out := new(GetAllBooksAndSort)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BookServer service

type BookServerHandler interface {
	Home(context.Context, *Empty, *StatusRsp) error
	Push(context.Context, *PostBook, *StatusUploadedBookRsp) error
	Book(context.Context, *GetBook, *GetBookRsp) error
	GetAllBooks(context.Context, *Empty, *GetAllBooks) error
	GetAllBooksAndSort(context.Context, *SortType, *GetAllBooksAndSort) error
}

func RegisterBookServerHandler(s server.Server, hdlr BookServerHandler, opts ...server.HandlerOption) error {
	type bookServer interface {
		Home(ctx context.Context, in *Empty, out *StatusRsp) error
		Push(ctx context.Context, in *PostBook, out *StatusUploadedBookRsp) error
		Book(ctx context.Context, in *GetBook, out *GetBookRsp) error
		GetAllBooks(ctx context.Context, in *Empty, out *GetAllBooks) error
		GetAllBooksAndSort(ctx context.Context, in *SortType, out *GetAllBooksAndSort) error
	}
	type BookServer struct {
		bookServer
	}
	h := &bookServerHandler{hdlr}
	return s.Handle(s.NewHandler(&BookServer{h}, opts...))
}

type bookServerHandler struct {
	BookServerHandler
}

func (h *bookServerHandler) Home(ctx context.Context, in *Empty, out *StatusRsp) error {
	return h.BookServerHandler.Home(ctx, in, out)
}

func (h *bookServerHandler) Push(ctx context.Context, in *PostBook, out *StatusUploadedBookRsp) error {
	return h.BookServerHandler.Push(ctx, in, out)
}

func (h *bookServerHandler) Book(ctx context.Context, in *GetBook, out *GetBookRsp) error {
	return h.BookServerHandler.Book(ctx, in, out)
}

func (h *bookServerHandler) GetAllBooks(ctx context.Context, in *Empty, out *GetAllBooks) error {
	return h.BookServerHandler.GetAllBooks(ctx, in, out)
}

func (h *bookServerHandler) GetAllBooksAndSort(ctx context.Context, in *SortType, out *GetAllBooksAndSort) error {
	return h.BookServerHandler.GetAllBooksAndSort(ctx, in, out)
}
