// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.4
// - protoc              v4.25.1
// source: main.proto

package pb

import (
	context "context"
	client "go.unistack.org/micro/v3/client"
)

var (
	BookServerName = "BookServer"
)

type BookServerClient interface {
	Home(ctx context.Context, req *Empty, opts ...client.CallOption) (*StatusRsp, error)
	Push(ctx context.Context, req *PostBook, opts ...client.CallOption) (*StatusUploadedBookRsp, error)
	Book(ctx context.Context, req *GetBook, opts ...client.CallOption) (*GetBookRsp, error)
	GetAllBooks(ctx context.Context, req *Empty, opts ...client.CallOption) (*GetAllBooks, error)
	GetAllBooksAndSort(ctx context.Context, req *SortType, opts ...client.CallOption) (*GetAllBooksAndSort, error)
}

type BookServerServer interface {
	Home(ctx context.Context, req *Empty, rsp *StatusRsp) error
	Push(ctx context.Context, req *PostBook, rsp *StatusUploadedBookRsp) error
	Book(ctx context.Context, req *GetBook, rsp *GetBookRsp) error
	GetAllBooks(ctx context.Context, req *Empty, rsp *GetAllBooks) error
	GetAllBooksAndSort(ctx context.Context, req *SortType, rsp *GetAllBooksAndSort) error
}
