// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: main.proto

package pb

import (
	_ "go.unistack.org/micro-proto/v3/api"
	_ "go.unistack.org/micro-proto/v3/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0}
}

type GetBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookTitle     string                 `protobuf:"bytes,1,opt,name=book_title,json=bookTitle,proto3" json:"book_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBook) Reset() {
	*x = GetBook{}
	mi := &file_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBook) ProtoMessage() {}

func (x *GetBook) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBook.ProtoReflect.Descriptor instead.
func (*GetBook) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{1}
}

func (x *GetBook) GetBookTitle() string {
	if x != nil {
		return x.BookTitle
	}
	return ""
}

type SortType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SortType      string                 `protobuf:"bytes,1,opt,name=sort_type,json=sortType,proto3" json:"sort_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortType) Reset() {
	*x = SortType{}
	mi := &file_main_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortType) ProtoMessage() {}

func (x *SortType) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortType.ProtoReflect.Descriptor instead.
func (*SortType) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{2}
}

func (x *SortType) GetSortType() string {
	if x != nil {
		return x.SortType
	}
	return ""
}

type GetAllBooks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []string               `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBooks) Reset() {
	*x = GetAllBooks{}
	mi := &file_main_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBooks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBooks) ProtoMessage() {}

func (x *GetAllBooks) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBooks.ProtoReflect.Descriptor instead.
func (*GetAllBooks) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllBooks) GetBooks() []string {
	if x != nil {
		return x.Books
	}
	return nil
}

type GetAllBooksAndSort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*GetBookRsp          `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBooksAndSort) Reset() {
	*x = GetAllBooksAndSort{}
	mi := &file_main_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBooksAndSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBooksAndSort) ProtoMessage() {}

func (x *GetAllBooksAndSort) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBooksAndSort.ProtoReflect.Descriptor instead.
func (*GetAllBooksAndSort) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllBooksAndSort) GetBooks() []*GetBookRsp {
	if x != nil {
		return x.Books
	}
	return nil
}

type PostBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookTitle     string                 `protobuf:"bytes,1,opt,name=book_title,json=bookTitle,proto3" json:"book_title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Genre         string                 `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	Year          string                 `protobuf:"bytes,4,opt,name=year,proto3" json:"year,omitempty"`
	BookBytes     []byte                 `protobuf:"bytes,5,opt,name=book_bytes,json=bookBytes,proto3" json:"book_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBook) Reset() {
	*x = PostBook{}
	mi := &file_main_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBook) ProtoMessage() {}

func (x *PostBook) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBook.ProtoReflect.Descriptor instead.
func (*PostBook) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{5}
}

func (x *PostBook) GetBookTitle() string {
	if x != nil {
		return x.BookTitle
	}
	return ""
}

func (x *PostBook) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PostBook) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *PostBook) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *PostBook) GetBookBytes() []byte {
	if x != nil {
		return x.BookBytes
	}
	return nil
}

type GetBookRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Genre         string                 `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	Year          string                 `protobuf:"bytes,4,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRsp) Reset() {
	*x = GetBookRsp{}
	mi := &file_main_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRsp) ProtoMessage() {}

func (x *GetBookRsp) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRsp.ProtoReflect.Descriptor instead.
func (*GetBookRsp) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{6}
}

func (x *GetBookRsp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetBookRsp) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *GetBookRsp) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *GetBookRsp) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

type StatusRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRsp) Reset() {
	*x = StatusRsp{}
	mi := &file_main_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRsp) ProtoMessage() {}

func (x *StatusRsp) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRsp.ProtoReflect.Descriptor instead.
func (*StatusRsp) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{7}
}

func (x *StatusRsp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type StatusUploadedBookRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUploadedBookRsp) Reset() {
	*x = StatusUploadedBookRsp{}
	mi := &file_main_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUploadedBookRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUploadedBookRsp) ProtoMessage() {}

func (x *StatusUploadedBookRsp) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUploadedBookRsp.ProtoReflect.Descriptor instead.
func (*StatusUploadedBookRsp) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{8}
}

func (x *StatusUploadedBookRsp) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

var File_main_proto protoreflect.FileDescriptor

const file_main_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"main.proto\x12\x0fbookservermicro\x1a\x15api/annotations.proto\x1a\x1bopenapiv3/annotations.proto\"\a\n" +
	"\x05Empty\"(\n" +
	"\agetBook\x12\x1d\n" +
	"\n" +
	"book_title\x18\x01 \x01(\tR\tbookTitle\"'\n" +
	"\bsortType\x12\x1b\n" +
	"\tsort_type\x18\x01 \x01(\tR\bsortType\"#\n" +
	"\vgetAllBooks\x12\x14\n" +
	"\x05books\x18\x01 \x03(\tR\x05books\"G\n" +
	"\x12getAllBooksAndSort\x121\n" +
	"\x05books\x18\x01 \x03(\v2\x1b.bookservermicro.getBookRspR\x05books\"\x8a\x01\n" +
	"\bpostBook\x12\x1d\n" +
	"\n" +
	"book_title\x18\x01 \x01(\tR\tbookTitle\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x14\n" +
	"\x05genre\x18\x03 \x01(\tR\x05genre\x12\x12\n" +
	"\x04year\x18\x04 \x01(\tR\x04year\x12\x1d\n" +
	"\n" +
	"book_bytes\x18\x05 \x01(\fR\tbookBytes\"d\n" +
	"\n" +
	"getBookRsp\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x14\n" +
	"\x05genre\x18\x03 \x01(\tR\x05genre\x12\x12\n" +
	"\x04year\x18\x04 \x01(\tR\x04year\"-\n" +
	"\tStatusRsp\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\"0\n" +
	"\x15statusUploadedBookRsp\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId2\x80\x06\n" +
	"\n" +
	"BookServer\x12|\n" +
	"\x04Home\x12\x16.bookservermicro.Empty\x1a\x1a.bookservermicro.StatusRsp\"@\xaa\x84\x9e\x032*\x04Home:*\n" +
	"(\x12&\n" +
	"$\n" +
	"\x10application/json\x12\x10\n" +
	"\x0e\x12\f\n" +
	"\n" +
	".StatusRsp\xb2\xea\xff\xf9\x01\x03\x12\x01/\x12\x9e\x01\n" +
	"\x04Push\x12\x19.bookservermicro.postBook\x1a&.bookservermicro.statusUploadedBookRsp\"S\xaa\x84\x9e\x03>*\x04Push:6\n" +
	"4\x122\n" +
	"0\n" +
	"\x10application/json\x12\x1c\n" +
	"\x1a\x12\x18\n" +
	"\x16.statusUploadedBookRsp\xb2\xea\xff\xf9\x01\n" +
	":\x01*\"\x05/push\x12\x84\x01\n" +
	"\x04Book\x12\x18.bookservermicro.getBook\x1a\x1b.bookservermicro.getBookRsp\"E\xaa\x84\x9e\x033*\x04Book:+\n" +
	")\x12'\n" +
	"%\n" +
	"\x10application/json\x12\x11\n" +
	"\x0f\x12\r\n" +
	"\v.getBookRsp\xb2\xea\xff\xf9\x01\a\x12\x05/book\x12\x96\x01\n" +
	"\vGetAllBooks\x12\x16.bookservermicro.Empty\x1a\x1c.bookservermicro.getAllBooks\"Q\xaa\x84\x9e\x03;*\vGetAllBooks:,\n" +
	"*\x12(\n" +
	"&\n" +
	"\x10application/json\x12\x12\n" +
	"\x10\x12\x0e\n" +
	"\f.getAllBooks\xb2\xea\xff\xf9\x01\v\x12\t/allbooks\x12\xb2\x01\n" +
	"\x12GetAllBooksAndSort\x12\x19.bookservermicro.sortType\x1a#.bookservermicro.getAllBooksAndSort\"\\\xaa\x84\x9e\x03I*\x12GetAllBooksAndSort:3\n" +
	"1\x12/\n" +
	"-\n" +
	"\x10application/json\x12\x19\n" +
	"\x17\x12\x15\n" +
	"\x13.getAllBooksAndSort\xb2\xea\xff\xf9\x01\b\x12\x06/booksB0Z.github.com/githubVladimirT/bookserver-micro;pbb\x06proto3"

var (
	file_main_proto_rawDescOnce sync.Once
	file_main_proto_rawDescData []byte
)

func file_main_proto_rawDescGZIP() []byte {
	file_main_proto_rawDescOnce.Do(func() {
		file_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_main_proto_rawDesc), len(file_main_proto_rawDesc)))
	})
	return file_main_proto_rawDescData
}

var file_main_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_main_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: bookservermicro.Empty
	(*GetBook)(nil),               // 1: bookservermicro.getBook
	(*SortType)(nil),              // 2: bookservermicro.sortType
	(*GetAllBooks)(nil),           // 3: bookservermicro.getAllBooks
	(*GetAllBooksAndSort)(nil),    // 4: bookservermicro.getAllBooksAndSort
	(*PostBook)(nil),              // 5: bookservermicro.postBook
	(*GetBookRsp)(nil),            // 6: bookservermicro.getBookRsp
	(*StatusRsp)(nil),             // 7: bookservermicro.StatusRsp
	(*StatusUploadedBookRsp)(nil), // 8: bookservermicro.statusUploadedBookRsp
}
var file_main_proto_depIdxs = []int32{
	6, // 0: bookservermicro.getAllBooksAndSort.books:type_name -> bookservermicro.getBookRsp
	0, // 1: bookservermicro.BookServer.Home:input_type -> bookservermicro.Empty
	5, // 2: bookservermicro.BookServer.Push:input_type -> bookservermicro.postBook
	1, // 3: bookservermicro.BookServer.Book:input_type -> bookservermicro.getBook
	0, // 4: bookservermicro.BookServer.GetAllBooks:input_type -> bookservermicro.Empty
	2, // 5: bookservermicro.BookServer.GetAllBooksAndSort:input_type -> bookservermicro.sortType
	7, // 6: bookservermicro.BookServer.Home:output_type -> bookservermicro.StatusRsp
	8, // 7: bookservermicro.BookServer.Push:output_type -> bookservermicro.statusUploadedBookRsp
	6, // 8: bookservermicro.BookServer.Book:output_type -> bookservermicro.getBookRsp
	3, // 9: bookservermicro.BookServer.GetAllBooks:output_type -> bookservermicro.getAllBooks
	4, // 10: bookservermicro.BookServer.GetAllBooksAndSort:output_type -> bookservermicro.getAllBooksAndSort
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_main_proto_init() }
func file_main_proto_init() {
	if File_main_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_main_proto_rawDesc), len(file_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_main_proto_goTypes,
		DependencyIndexes: file_main_proto_depIdxs,
		MessageInfos:      file_main_proto_msgTypes,
	}.Build()
	File_main_proto = out.File
	file_main_proto_goTypes = nil
	file_main_proto_depIdxs = nil
}
