// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.4
// - protoc              v3.19.6
// source: main.proto

package pb

import (
	context "context"
	v3 "go.unistack.org/micro-server-http/v3"
	client "go.unistack.org/micro/v3/client"
)

var (
	BookServerName = "BookServer"
)
var (
	BookServerServerEndpoints = []v3.EndpointMetadata{
		{
			Name:   "BookServer.Home",
			Path:   "/",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
		{
			Name:   "BookServer.Push",
			Path:   "/push",
			Method: "POST",
			Body:   "*",
			Stream: false,
		},
		{
			Name:   "BookServer.Book",
			Path:   "/book",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
		{
			Name:   "BookServer.GetAllBooks",
			Path:   "/allbooks",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
		{
			Name:   "BookServer.GetAllBooksAndSort",
			Path:   "/books",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
	}
)

type BookServerClient interface {
	Home(ctx context.Context, req *Empty, opts ...client.CallOption) (*StatusRsp, error)
	Push(ctx context.Context, req *PostBook, opts ...client.CallOption) (*StatusUploadedBookRsp, error)
	Book(ctx context.Context, req *GetBook, opts ...client.CallOption) (*GetBookRsp, error)
	GetAllBooks(ctx context.Context, req *Empty, opts ...client.CallOption) (*GetAllBooks, error)
	GetAllBooksAndSort(ctx context.Context, req *SortType, opts ...client.CallOption) (*GetAllBooksAndSort, error)
}

type BookServerServer interface {
	Home(ctx context.Context, req *Empty, rsp *StatusRsp) error
	Push(ctx context.Context, req *PostBook, rsp *StatusUploadedBookRsp) error
	Book(ctx context.Context, req *GetBook, rsp *GetBookRsp) error
	GetAllBooks(ctx context.Context, req *Empty, rsp *GetAllBooks) error
	GetAllBooksAndSort(ctx context.Context, req *SortType, rsp *GetAllBooksAndSort) error
}
